### ISSUE TITLE
Cloud: Crash when using a react hook in top-level app compoonent.

### ISSUE THREAD

**Issue by brentjett** [beaverbuilder/assistant#242]
There's a strange issue when you use a hook in the top-level component of an app. As soon as you navigate to another app, you'll get a react error saying a different number of hooks were used and you'll see the error boundary message. 

<img width="881" alt="Screen Shot 2020-03-29 at 9 15 07 PM" src="https://user-images.githubusercontent.com/1790660/77869122-01ddc180-7203-11ea-9156-f81ca2a2fbf2.png">

Using hooks further down the component tree don't seem to cause this issue. Not quite sure if this is a bug that can be fixed or just a behavior we need to be aware of, perhaps related to react-router-dom.

**Comment by phredeye** [comment]
I'm not sure what to do with this.  Most of that code should be going away
soon. There will be a very similar token based auth flow that is not jwt
based.  As far as i'm concerned, feel free to do whatever needs to be done
to make the error go away, or im not sure if Justin has some other ideas.
It can't be working because we dont have a cloud prototype up right now.
We should in a few days.

**Comment by brentjett** [comment]
Sorry Fred, this was mainly for @fastlinemedia cause he's been working in the cloud app. Nothing you need to worry about right now.

**Comment by fastlinemedia** [comment]
Man this is a strange error! I dug into it and it definitely looks like something weird is going on with React Router. I'll just throw that in a subcomponent for now. Couldn't figure it out.

**Comment by fastlinemedia** [comment]
Spoke too soon! Fixed it in the `AppContent` component. I'll push that shortly.
